inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2

Layout/AlignArguments:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Layout/DotPosition:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

# We use this a lot in specs where it's perfectly valid
Lint/Void:
  Exclude:
    - spec/**/*

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# This hides the has-a versus is-a relationship indicated by the method name
Naming/PredicateName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

# We have too much code that relies on modifying strings
Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

# TODO: Address these at some point
Style/MethodMissingSuper:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

# Prefer curly braces except for %i/%w/%W, since those return arrays.
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '{}'
    '%i': '[]'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'
    '%s': '()'
    '%w': '[]'
    '%W': '[]'
    '%x': '{}'

Style/PerlBackrefs:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/WhenThen:
  Enabled: false
