class MockRedis
  module InfoMethod
    def info
      {
        "aof_enabled" => "0",
        "arch_bits" => "64",
        "bgrewriteaof_in_progress" => "0",
        "bgsave_in_progress" => "0",
        "blocked_clients" => "0",
        "changes_since_last_save" => "0",
        "client_biggest_input_buf" => "0",
        "client_longest_output_list" => "0",
        "connected_clients" => "1",
        "connected_slaves" => "0",
        "db0" => "keys=8,expires=0",
        "evicted_keys" => "0",
        "expired_keys" => "0",
        "hash_max_zipmap_entries" => "512",
        "hash_max_zipmap_value" => "64",
        "keyspace_hits" => "62645",
        "keyspace_misses" => "29757",
        "last_save_time" => "1310596333",
        "loading" => "0",
        "lru_clock" => "1036434",
        "mem_fragmentation_ratio" => "2.04",
        "multiplexing_api" => "kqueue",
        "process_id" => "14508",
        "pubsub_channels" => "0",
        "pubsub_patterns" => "0",
        "redis_git_dirty" => "0",
        "redis_git_sha1" => "00000000",
        "redis_version" => "2.2.11",
        "role" => "master",
        "total_commands_processed" => "196800",
        "total_connections_received" => "4359",
        "uptime_in_days" => "0",
        "uptime_in_seconds" => "84215",
        "use_tcmalloc" => "0",
        "used_cpu_sys" => "5.54",
        "used_cpu_sys_childrens" => "0.00",
        "used_cpu_user" => "7.65",
        "used_cpu_user_childrens" => "0.02",
        "used_memory" => "931456",
        "used_memory_human" => "909.62K",
        "used_memory_rss" => "1904640",
        "vm_enabled" => "0",
      }
    end
  end
end

